services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: lorawan_mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./infra/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    container_name: lorawan_influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUX_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUX_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUX_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_TOKEN}
    volumes:
      - influxdb-data:/var/lib/influxdb2
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.1.0
    container_name: lorawan_grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
    restart: unless-stopped

  publisher:
    build:
      context: .
      dockerfile: infra/docker/python-app.Dockerfile
    container_name: lorawan_publisher
    command: ["python", "model/random_data_publisher.py"]
    environment:
      MQTT_HOST: mqtt
      MQTT_PORT: 1883
      MQTT_TOPIC_BASE: hive
      DEVICE_ID: ruche-01
      PUBLISH_INTERVAL_SECONDS: ${PUBLISH_INTERVAL_SECONDS}
      SCENARIO: ${SCENARIO:-normal}
      SPIKE_PROBABILITY: ${SPIKE_PROBABILITY:-0.08}
      LORAWAN_PDR: ${LORAWAN_PDR:-0.9}
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      INFLUX_ORG: ${INFLUX_ORG}
      INFLUX_BUCKET: ${INFLUX_BUCKET}
    depends_on:
      - mqtt
    restart: unless-stopped

  ingestion:
    build:
      context: .
      dockerfile: infra/docker/python-app.Dockerfile
    container_name: lorawan_ingestion
    command: ["python", "model/mqtt_to_influx.py"]
    environment:
      MQTT_HOST: mqtt
      MQTT_PORT: 1883
      MQTT_TOPIC: hive/+/telemetry
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      INFLUX_ORG: ${INFLUX_ORG}
      INFLUX_BUCKET: ${INFLUX_BUCKET}
      INFLUX_MEASUREMENT: hive_telemetry
    depends_on:
      - mqtt
      - influxdb
    restart: unless-stopped

volumes:
  influxdb-data:
  grafana-data:
